version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          actions-breaking:
              applies-to: version-updates
              update-types:
                  - major
          actions-safe-updates:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch

    - package-ecosystem: "npm"
      directory: "/elsa"
      schedule:
          interval: "weekly"
      groups:
          elsa-npm-breaking:
              applies-to: version-updates
              update-types:
                  - major

          elsa-npm-safe:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch

    - package-ecosystem: "npm"
      directory: "/tools"
      schedule:
          interval: "weekly"
      groups:
          tools-npm-breaking:
              applies-to: version-updates
              update-types:
                  - major

          tools-npm-safe:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch
